language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# Command to install dependencies
sudo: false

# Install packages
install:
  #- conda install --yes python=$TRAVIS_PYTHON_VERSION nose
  - pip install nose scripttest
  - python setup.py install

# Command to run tests
script: nosetests -v 

branches:
    only:
        - master

notifications:
    email:
        recipients:
            - gmatteo@gmail.com
        on_success: change
        on_failure: always

# Calculate coverage
#after_success:
#       - coveralls --config_file .coveragerc
