language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

sudo: required

# Install packages
install:
  #- conda install --yes python=$TRAVIS_PYTHON_VERSION nose
  - pip install pytest scripttest
  - python setup.py install

# Command to run tests
script: py.test -v

branches:
    only:
        - master

notifications:
    email:
        recipients:
            - gmatteo@gmail.com
        on_success: change
        on_failure: always

# Calculate coverage
#after_success:
#       - coveralls --config_file .coveragerc
